#include "pb12.h"

const char *pb12ErrorStr[] = {
    "ERROR: Invalid first pointer register\n",
    "ERROR: Invalid second pointer register\n",
    "ERROR: Invalid first general register\n",
    "ERROR: Invalid second general register\n",
    "ERROR: Address out of range\n",
    "ERROR: Invalid opcode\n",
    "ERROR: Address out of range (ear=%d, bar=%d, lr=%d)\n",
    "ERROR: Ran out of space for new processes.\n",
    "ERROR: Process %d cannot be destroyed.\n",
    "ERROR: Process %d does not exist.\n",
    "ERROR: Could not execute '%s'.\n",
    "ERROR: initializing CPU.\n",
    "ERROR: initializing memory.\n",
    "ERROR: initializing operating system.\n",
    "ERROR: PCB not found in list.\n",
    "ERROR: Could not move first PCB to top.\n"

};


const char *pb12InstDesc[] = {
    "Load Pointer Immediate",
    "Add to Pointer Immediate",
    "Subtract from Pointer Immediate",
    "Load Accumulator Immediate",
    "Load Accumulator Register Addressing",
    "Load Accumulator Direct Addressing",
    "Store Accumulator Register Addressing",
    "Store Accumulator Direct Addressing",
    "Store Register to Memory: Register Addressing",
    "Store Register to Memory: Direct Addressing",
    "Load Register from Memory: Register Addressing",
    "Load Register from Memory: Direct Addressing",
    "Load Register R0 Immediate",
    "Register to Register Transfer",
    "Load Accumulator from Register",
    "Load Register from Accumulator",
    "Add Accumulator Immediate",
    "Subtract Accumulator Immediate",
    "Add contents of Register from Accumulator",
    "Subtract contents of Register from Accumulator",
    "Add Accumulator Register Addressing",
    "Add Accumulator Direct Addressing",
    "Subtract from Accumulator Register Addressing",
    "Subtract from Accumulator Direct Addressing",
    "Compare Equal Register Addressing",
    "Compare Less Register Addressing",
    "Compare Greater Register Addressing",
    "Compare Greater Immediate",
    "Compare Equal Immediate",
    "Compare Less Immediate",
    "Compare Register Equal",
    "Compare Register Less",
    "Compare Register Greater",
    "Branch Condition True",
    "Branch Condition False",
    "Branch Unconditional",
    "Trap Instruction",
    "Modulo Operator",
    "Halt"
};
